### ISSUE TITLE
Line spacing too small in new reddit styles

### ISSUE THREAD

**Issue by Ved-un** [iampueroo/rComments#22] opened 2021-05-13 20:58 UTC
Nice addon.
But is it possible to increase the line spacing?
or reduce the font?

https://i.imgur.com/HSmMnDI.png

Difficult to read, lines merge.

**Comment by iampueroo** [comment] 2021-05-14 20:11
Thanks @Ved-un for the much needed issue. I've upped the styles and below are the previews. I'll be publishing a new version and you should be seeing it next week. I'll keep this issue open until then!

Firefox - Before             |  Firefox - After
:-------------------------:|:-------------------------:
![](https://i.imgur.com/MLVno1e.png)  |  ![](https://i.imgur.com/KmSMi38.png)


Chrome - Before             |  Chrome - After
:-------------------------:|:-------------------------:
![](https://i.imgur.com/ainf34G.png)  |  ![](https://i.imgur.com/qNRLNSB.png)

**Comment by iampueroo** [comment] 2021-05-14 20:17
Note to self: this improvement only affects new Reddit styles, not `old.reddit.com`, as the elements inherit the `line-height` and `<p>` margin styles from Reddit's stylesheets.

**Comment by iampueroo** [comment] 2021-05-17 17:41
@Ved-un I'm resolving this as I published the new version with improved line and paragraph spacing. It is now available in [Firefox](https://addons.mozilla.org/en-US/firefox/addon/rcomments/versions/) and soon in [Chrome](https://chrome.google.com/webstore/detail/rcomments-reddit-hover-co/njkilkdmdolbjonbfjhmknefhdccioig) (once the version gets approved). Feel free to reopen if there are further line-spacing issues.

Please note that I found out that the root cause of this issue (Reddit styles are not being applied to the extension's popup) also means that most of the supported markdown one can use on Reddit comments isn't being supported either. I opened up issue #23 in to track and fix with the next version. Note that this bug does not exist on old Reddit, as the stylesheet issue is not a problem on there. 

Thanks again for submitting the issue!

**Closed by iampueroo** 2021-05-17 17:41 UTC
